Repository catalyst-cooperative/pudl-archiver, pull requests merged in 2023-02, with the labels that each got.

#59 Debug retry logic
  .github/workflows/run-archiver.yml
  src/pudl_archiver/archivers/classes.py
  src/pudl_archiver/archivers/ferc/xbrl.py
  src/pudl_archiver/depositors/zenodo.py
  src/pudl_archiver/utils.py
  tests/unit/archive_base_test.py
  tests/unit/utils_test.py
  tests/unit/xbrl_test.py
Labels: inframundo

#49 Archive PHMSA gas annual reports
  dataset_doi.yaml
  src/pudl_archiver/archivers/phmsagas.py
Labels: inframundo

#63 Fix `--dry-run` option
  README.md
  src/pudl_archiver/orchestrator.py
Labels: inframundo

#69 Delete draft if there were no changes to make
  src/pudl_archiver/depositors/zenodo.py
  src/pudl_archiver/orchestrator.py
  tests/integration/zenodo_depositor_test.py
  tests/integration/zenodo_test.py
Labels: inframundo

#78 Update EIA Water link regex for 2021 files
  src/pudl_archiver/archivers/eiawater.py
Labels: inframundo, eiawater

#82 Standardize filenames and add production DOIs
  .github/workflows/run-archiver.yml
  dataset_doi.yaml
  src/pudl_archiver/archivers/mshamines.py
  src/pudl_archiver/archivers/phmsagas.py
Labels: eia176, inframundo, eiawater, zenodo, phmsagas, mshamines
