Repository catalyst-cooperative/pudl-archiver, pull requests merged in 2024-01, with the labels that each got.

#202 Add flag to refresh metadata for existing depositions
  src/pudl_archiver/__init__.py
  src/pudl_archiver/cli.py
  src/pudl_archiver/depositors/zenodo.py
  src/pudl_archiver/orchestrator.py
  tests/integration/zenodo_test.py
Labels: metadata

#252 Change PHMSA partitions to use `year` instead of `years`
  src/pudl_archiver/archivers/phmsagas.py
Labels: metadata, phmsagas

#253 When PHMSA data has `_present` in file name, make partitions actually reflect years of data available correctly.
  src/pudl_archiver/archivers/phmsagas.py
Labels: metadata, phmsagas

#257 Add `eia_bulk_elec` to monthly automated archiver runs
  .github/workflows/run-archiver.yml
  environment.yml
Labels: new-data, automation

#261 Add explicit frictionless dependency since we import it direclty.
  pyproject.toml
Labels: dependencies

#268 Update zipfile type check validation and add file checks into summary JSON files
  src/pudl_archiver/archivers/validate.py
  tests/unit/archive_base_test.py
Labels: bug, automation
