Repository catalyst-cooperative/pudl-archiver, pull requests merged in 2024-06, with the labels that each got.

#326 Remove --dry-run CLI option and references
  README.md
  src/pudl_archiver/cli.py
  src/pudl_archiver/depositors/depositor.py
  src/pudl_archiver/utils.py
  tests/integration/zenodo_test.py
Labels: community

#354 Bump GDAL to 3.9.0 explicitly to align with PUDL dependencies
  .github/workflows/tox-pytest.yml
  environment.yml
  pyproject.toml
  tox.ini
Labels: dependencies

#357 MVP improvements to automated archive runs
  .github/ISSUE_TEMPLATE/monthly-archive-update.md
  .github/workflows/run-archiver.yml
  scripts/make_slack_notification_message.py
Labels: github_actions, automation

#365 Remove outdated fiona dependency (as of geopandas v1.0)
  environment.yml
Labels: dependencies
